<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <None Update="img\calendar.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="img\github.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="img\globe.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="img\ok.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="img\plus.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="img\search.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="img\vk.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="img\youtube.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="settings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\search-engine.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\cat.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
